version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: always
    volumes:
      - postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nucleus
      POSTGRES_PASSWORD: nucleus
      POSTGRES_DB: nucleus
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
  redis:
    image: bitnami/redis:latest
    container_name: redis
    hostname: redis
    privileged: false
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 6379:6379
    env_file:
      - .env
    volumes:
      - redisdb:/bitnami/redis/data
  mailgun:
    image: asedov/mailgun-mock
    container_name: mailgun
    ports:
      - 4600:80
    environment:
      - MAILGUN_API_KEY=${MAILGUN_API_KEY:-secret-key}
volumes:
  postgresdb:
  redisdb:
